theme: minima
title: "Houceine's Portfolio"
description: "Web Design Services Portfolio"
header_pages:
  - index.md
  - about.md
  - services.md
  - portfolio.md
  - contact.md

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .git/
  - .github/ 